In [1]:
import pandas as pd
import numpy as np

In [89]:
df=pd.read_csv('Bank_Churn.csv')
df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerId       10000 non-null  int64
 1   Surname          10000 non-null  object
 2   CreditScore      10000 non-null  int64
 3   Geography        10000 non-null  object
 4   Gender           10000 non-null  object
 5   Age              10000 non-null  int64
 6   Tenure           10000 non-null  int64
 7   Balance          10000 non-null  float64
 8   NumOfProducts    10000 non-null  int64
 9   HasCrCard        10000 non-null  int64
 10  IsActiveMember   10000 non-null  int64
 11  EstimatedSalary  10000 non-null  float64
 12  Exited           10000 non-null  int64
dtypes: float64(2), int64(8), object(3)
memory usage: 1015.8+ KB

In [5]:
df.describe()

,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

check for duplicacy in dataset , and specify the row of duplicacy

In [25]:
df[df.duplicated()]

Empty DataFrame
Columns: [CustomerId, Surname, CreditScore, Geography, Gender, Age, Tenure, Balance, NumOfProducts, HasCrCard, IsActiveMember, EstimatedSalary, Exited]
Index: []

duplicacy check for particular column

In [26]:
df.duplicated(subset=['CustomerId'])

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

#creating the age group using the lables and qcuts

In [91]:
lable=['young_adult','adult','mid_age','old_age']
df['age_group']=pd.qcut(df['Age'],q=4,labels=lable)
df.head(10)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,age_group
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,mid_age
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,mid_age
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,mid_age
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,mid_age
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,mid_age
5,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1,mid_age
6,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0,old_age
7,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1,young_adult
8,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0,mid_age
9,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0,young_adult

In [94]:
lablee=['new','repeat','old_customer']
df['tenure_group']=pd.qcut(df['tenure'],q=3,labels=lablee)
lab=['Poor','Fair','Good','Excellent']
df['credit_score_group']=pd.qcut(df['credit_score'],q=4,labels=lab)
df.head(10)

,customer_id,Surname,credit_score,geography,gender,age,tenure,balance,num_of_products,has_cr_card,is_active_member,estimated_salary,exited,age_group,tenure_group,credit_score_group
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,mid_age,new,Fair
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,mid_age,new,Fair
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,mid_age,old_customer,Poor
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,mid_age,new,Good
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,mid_age,new,Excellent
5,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1,mid_age,old_customer,Fair
6,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0,old_age,repeat,Excellent
7,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1,young_adult,repeat,Poor
8,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0,mid_age,repeat,Poor
9,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0,young_adult,new,Good

In [44]:
# <!-- renaming the columns  -->
df.columns

Index(['CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age',
       'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited', 'age_group', 'tenure_group'],
      dtype='object')

In [93]:
df.rename(columns={'CustomerId':'customer_id','CreditScore':'credit_score','Geography':'geography','Gender':'gender','Age':'age','Tenure':'tenure',
'Balance':'balance','NumOfProducts':'num_of_products' ,'HasCrCard':'has_cr_card','IsActiveMember':'is_active_member','EstimatedSalary':'estimated_salary'  ,
               'Exited':'exited'},inplace=True)

In [95]:
mapping={
    1:"yes",
    0:'no'
}
df['active_Status']=df['is_active_member'].map(mapping)
df['credit_cr_status']=df['has_cr_card'].map(mapping)
df.drop(['has_cr_card','is_active_member'],axis=1,inplace=True)
df.head()

,customer_id,Surname,credit_score,geography,gender,age,tenure,balance,num_of_products,estimated_salary,exited,age_group,tenure_group,credit_score_group,active_Status,credit_cr_status
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,101348.88,1,mid_age,new,Fair,yes,yes
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,112542.58,0,mid_age,new,Fair,yes,no
2,15619304,Onio,502,France,Female,42,8,159660.80,3,113931.57,1,mid_age,old_customer,Poor,no,yes
3,15701354,Boni,699,France,Female,39,1,0.00,2,93826.63,0,mid_age,new,Good,no,no
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,79084.10,0,mid_age,new,Excellent,yes,yes

In [97]:
import pandas as pd
from sqlalchemy import create_engine

# Create connection with MySQL
engine = create_engine("mysql+pymysql://root:KATOCHshaab%401@127.0.0.1:3306/Bank_db")
# Export dataframe to MySQL table
df.to_sql(
    name='customer',
    con=engine,
    if_exists='replace',
    index=False
)

print("Data exported successfully!")

Data exported successfully!

In [80]:
df.head()

,customer_id,Surname,credit_score,geography,gender,age,tenure,balance,num_of_products,estimated_salary,exited,age_group,tenure_group,active_Status,credit_cr_status
0,15634602,Hargrave,Fair,France,Female,42,2,0.00,1,101348.88,1,mid_age,new,yes,yes
1,15647311,Hill,Fair,Spain,Female,41,1,83807.86,1,112542.58,0,mid_age,new,yes,no
2,15619304,Onio,Poor,France,Female,42,8,159660.80,3,113931.57,1,mid_age,old_customer,no,yes
3,15701354,Boni,Good,France,Female,39,1,0.00,2,93826.63,0,mid_age,new,no,no
4,15737888,Mitchell,Excellent,Spain,Female,43,2,125510.82,1,79084.10,0,mid_age,new,yes,yes

In [98]:
df.describe()

,customer_id,credit_score,age,tenure,balance,num_of_products,estimated_salary,exited
count,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,100090.239881,0.203700
std,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,57510.492818,0.402769
min,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,11.580000,0.000000
25%,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,51002.110000,0.000000
50%,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,100193.915000,0.000000
75%,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,149388.247500,0.000000
max,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,199992.480000,1.000000

In [96]:
lable1=['low_wage','mid_wage','high_wage']
lable2=['low','mid','high']
df['estimated_salary_group']=pd.qcut(df['estimated_salary'],q=3,labels=lable1)
df['balance_group']=pd.qcut(df['balance'],q=4,labels=lable2,duplicates='drop')
df.head()

,customer_id,Surname,credit_score,geography,gender,age,tenure,balance,num_of_products,estimated_salary,exited,age_group,tenure_group,credit_score_group,active_Status,credit_cr_status,estimated_salary_group,balance_group
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,101348.88,1,mid_age,new,Fair,yes,yes,mid_wage,low
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,112542.58,0,mid_age,new,Fair,yes,no,mid_wage,low
2,15619304,Onio,502,France,Female,42,8,159660.80,3,113931.57,1,mid_age,old_customer,Poor,no,yes,mid_wage,high
3,15701354,Boni,699,France,Female,39,1,0.00,2,93826.63,0,mid_age,new,Good,no,no,mid_wage,low
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,79084.10,0,mid_age,new,Excellent,yes,yes,mid_wage,mid